---
title: "Developing Data Product Week 4 Assignment Presentation"
author: "Ngiam Pei Yee"
date: "6/13/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Coursera Reproducible Pitch

This is a task for the data science coursera course about developing data products for week 4. As part of this, I have created a shiny app and deployed it on the shiny server. The link is https://ngiampy88.shinyapps.io/MyShinyApp/. The code can be found at 

## Application Overview

- The application is written in Shiny which is a web application framework for R
- The source code consists of two files: server.R and ui.R
- server.R includes the the server logic of a Shiny web application
- ui.R includes the the user-interface definition, which uses the sidebarLayout template
- The application is hosted on Rstudio's shiny server in the cloud (Shinyapps.io)

## Overview

The shiny app plots graph against miles per gallon (mpg) for different variables from the mtcars dataset.

- Click the dropdown list to choose the variable you would like to plot against mpg
- Output: Plot of the requested variable against mpg

## Ready to give it a try?

Use the Shiny app at https://ngiampy88.shinyapps.io/MyShinyApp/

Get the app source code at 
